plugins:
  - react

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

extends:
  - eslint-config-wantora
  - plugin:react/recommended

env:
  es6: true
  browser: true
  commonjs: true

globals:
  process: false

rules:
  no-shadow: ["error", {"builtinGlobals": true, "allow": ["name"]}]
